language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - npm install
script:
  - flake8 .
  - ./node_modules/.bin/eslint static/scripts/script.js